from __future__ import annotations

PRODUCT_ORDER = [
    "gutsol_liquid",
    "gutsol_powder",
    "immon_layer",
    "immon_broiler",
    "colikil_r",
    "colikil_liquid",
    "crdx_ir",
    "thermogard_prevention",
    "thermogard_treatment",
]

PRODUCT_DEFINITIONS = {
    "gutsol_liquid": {
        "product_name": "Gutsol Liquid",
        "category": "Gut Health",
        "application": "Liquid feed additive",
        "form": "Liquid",
        "calculation_engine": "gutsol_liquid",
        "inputs": [
            {"id": "flock_size", "label": "Flock Size", "default": 10000, "unit": "birds", "min": 1},
            {"id": "gutsol_cost_per_bird_day", "label": "Gutsol Cost/Bird/Day", "default": 0.03, "unit": "₹/bird/day", "min": 0},
            {"id": "duration_days", "label": "Duration", "default": 7, "unit": "days", "min": 1},
            {"id": "live_bird_price", "label": "Live Bird Price", "default": 100, "unit": "₹/kg", "min": 0},
            {"id": "extra_weight_gain_g", "label": "Extra Weight/Bird", "default": 30, "unit": "g/bird", "min": 0},
            {"id": "mortality_reduction_pct", "label": "Mortality Reduction", "default": 0.25, "unit": "%", "min": 0, "max": 100},
            {"id": "average_bird_weight_kg", "label": "Average Bird Weight", "default": 2.2, "unit": "kg", "min": 0},
        ],
        "output_metrics": ["investment_total", "benefit_total", "net_profit_total", "roi", "benefit_per_bird", "cost_per_bird"],
        "benefit_components": ["weight_gain_benefit", "mortality_benefit"],
    },
    "gutsol_powder": {
        "product_name": "Gutsol Powder",
        "category": "Gut Health",
        "application": "Powder feed additive",
        "form": "Powder",
        "calculation_engine": "gutsol_powder",
        "inputs": [
            {"id": "flock_size", "label": "Flock Size", "default": 10000, "unit": "birds", "min": 1},
            {"id": "body_weight_kg", "label": "Body Weight", "default": 2.3, "unit": "kg", "min": 0},
            {"id": "fcr", "label": "FCR", "default": 1.45, "unit": "kg feed/kg gain", "min": 0.01},
            {"id": "dose_g_per_ton", "label": "Dose", "default": 250, "unit": "g/ton", "min": 0},
            {"id": "product_price_per_kg", "label": "Product Price", "default": 600, "unit": "₹/kg", "min": 0},
            {"id": "live_bird_price", "label": "Live Bird Price", "default": 100, "unit": "₹/kg", "min": 0},
            {"id": "extra_weight_gain_g", "label": "Extra Weight Gain/Bird", "default": 50, "unit": "g/bird", "min": 0},
            {"id": "mortality_reduction_pct", "label": "Mortality Reduction", "default": 0.25, "unit": "%", "min": 0, "max": 100},
            {"id": "average_bird_weight_kg", "label": "Average Bird Weight Saved", "default": 2.3, "unit": "kg", "min": 0},
        ],
        "output_metrics": ["investment_total", "benefit_total", "net_profit_total", "roi", "benefit_per_bird", "cost_per_bird"],
        "benefit_components": ["weight_gain_benefit", "mortality_benefit"],
    },
    "immon_layer": {
        "product_name": "Immon Layer Powder",
        "category": "Layer Performance",
        "application": "Egg production improvement",
        "form": "Powder",
        "calculation_engine": "immon_layer",
        "inputs": [
            {"id": "flock_size", "label": "Flock Size", "default": 10000, "unit": "layers", "min": 1},
            {"id": "trial_duration_days", "label": "Trial Duration", "default": 266, "unit": "days", "min": 1},
            {"id": "egg_production_control_pct", "label": "Control HDP", "default": 89.19, "unit": "%", "min": 0, "max": 100},
            {"id": "egg_production_treatment_pct", "label": "Treatment HDP", "default": 91.66, "unit": "%", "min": 0, "max": 100},
            {"id": "egg_selling_price", "label": "Egg Selling Price", "default": 5.6, "unit": "₹/egg", "min": 0},
            {"id": "product_cost_per_bird_day", "label": "Product Cost", "default": 0.0152, "unit": "₹/bird/day", "min": 0},
            {"id": "mortality_saved_pct", "label": "Mortality Saved", "default": 0.75, "unit": "%", "min": 0, "max": 100},
            {"id": "value_per_layer", "label": "Value per Layer", "default": 350, "unit": "₹/bird", "min": 0},
        ],
        "output_metrics": ["investment_total", "benefit_total", "net_profit_total", "roi", "additional_egg_revenue", "egg_benefit"],
        "benefit_components": ["egg_revenue", "mortality_benefit"],
    },
    "immon_broiler": {
        "product_name": "Immon Broiler Mortality",
        "category": "Broiler Performance",
        "application": "Mortality and weight improvement",
        "form": "Powder",
        "calculation_engine": "immon_broiler",
        "inputs": [
            {"id": "flock_size", "label": "Flock Size", "default": 10000, "unit": "birds", "min": 1},
            {"id": "immon_cost_per_bird_day", "label": "Cost of Immon", "default": 1.52, "unit": "₹/bird/day (paise)", "min": 0},
            {"id": "trial_duration_days", "label": "Trial Duration", "default": 35, "unit": "days", "min": 1},
            {"id": "control_body_weight_kg", "label": "Control BW", "default": 2.05, "unit": "kg", "min": 0},
            {"id": "treatment_body_weight_kg", "label": "Treatment BW", "default": 2.15, "unit": "kg", "min": 0},
            {"id": "live_bird_price", "label": "Live Bird Price", "default": 100, "unit": "₹/kg", "min": 0},
            {"id": "control_mortality_pct", "label": "Control Mortality", "default": 5, "unit": "%", "min": 0, "max": 100},
            {"id": "treatment_mortality_pct", "label": "Treatment Mortality", "default": 4, "unit": "%", "min": 0, "max": 100},
        ],
        "output_metrics": ["investment_total", "benefit_total", "net_profit_total", "roi", "weight_gain_benefit", "mortality_benefit"],
        "benefit_components": ["weight_gain_benefit", "mortality_benefit"],
    },
    "colikil_r": {
        "product_name": "Colikil-R Powder",
        "category": "Feed Efficiency",
        "application": "Broiler prevention",
        "form": "Powder",
        "calculation_engine": "colikil_r",
        "inputs": [
            {"id": "flock_size", "label": "Flock Size", "default": 10000, "unit": "birds", "min": 1},
            {"id": "live_bird_price", "label": "Live Bird Price", "default": 100, "unit": "₹/kg", "min": 0},
            {"id": "feed_price_per_kg", "label": "Feed Price", "default": 40, "unit": "₹/kg", "min": 0},
            {"id": "product_price_per_kg", "label": "Product Price", "default": 750, "unit": "₹/kg", "min": 0},
            {"id": "control_body_weight_kg", "label": "Control BW", "default": 1.911, "unit": "kg", "min": 0},
            {"id": "treatment_body_weight_kg", "label": "Treatment BW", "default": 1.975, "unit": "kg", "min": 0},
            {"id": "control_fcr", "label": "Control FCR", "default": 1.626, "unit": "FCR", "min": 0.01},
            {"id": "treatment_fcr", "label": "Treatment FCR", "default": 1.564, "unit": "FCR", "min": 0.01},
            {"id": "dose_g_per_ton", "label": "Dose", "default": 150, "unit": "g/ton", "min": 0},
        ],
        "output_metrics": ["investment_total", "benefit_total", "net_profit_total", "roi", "benefit_per_bird", "cost_per_bird"],
        "benefit_components": ["weight_gain_benefit", "feed_saving_benefit"],
    },
    "colikil_liquid": {
        "product_name": "Colikil Liquid",
        "category": "Liquid Feed Additive",
        "application": "Prevention",
        "form": "Liquid",
        "calculation_engine": "colikil_liquid",
        "inputs": [
            {"id": "flock_size", "label": "Flock Size", "default": 10000, "unit": "birds", "min": 1},
            {"id": "live_bird_price", "label": "Live Bird Price", "default": 100, "unit": "₹/kg", "min": 0},
            {"id": "product_price_per_liter", "label": "Product Price", "default": 1800, "unit": "₹/L", "min": 0},
            {"id": "medication_hours_day", "label": "Medication Hours/Day", "default": 12, "unit": "hours/day", "min": 0},
            {"id": "treatment_days", "label": "Treatment Days", "default": 20, "unit": "days", "min": 1},
            {"id": "water_intake_l_per_day", "label": "Average Water Intake", "default": 0.2, "unit": "L/bird/day", "min": 0},
            {"id": "dose_l_per_ml", "label": "Dose", "default": 2, "unit": "L water / 1 mL product", "min": 0},
            {"id": "control_body_weight_kg", "label": "Control BW", "default": 2.181, "unit": "kg", "min": 0},
            {"id": "treatment_body_weight_kg", "label": "Treatment BW", "default": 2.247, "unit": "kg", "min": 0},
        ],
        "output_metrics": ["investment_total", "benefit_total", "net_profit_total", "roi", "benefit_per_bird", "cost_per_bird"],
        "benefit_components": ["weight_gain_benefit"],
    },
    "crdx_ir": {
        "product_name": "CRDX-IR Liquid",
        "category": "Respiratory Support",
        "application": "Prevention of respiratory issues",
        "form": "Liquid",
        "calculation_engine": "crdx_ir",
        "inputs": [
            {"id": "flock_size", "label": "Flock Size", "default": 10000, "unit": "birds", "min": 1},
            {"id": "live_bird_price", "label": "Live Bird Price", "default": 100, "unit": "₹/kg", "min": 0},
            {"id": "product_price_per_liter", "label": "CRDX-IR Price", "default": 4400, "unit": "₹/L", "min": 0},
            {"id": "dose_ml_per_1000_birds_day", "label": "Dose", "default": 10, "unit": "mL/1000 birds/day", "min": 0},
            {"id": "treatment_days", "label": "Treatment Days", "default": 42, "unit": "days", "min": 1},
            {"id": "control_body_weight_kg", "label": "Control BW", "default": 2.738, "unit": "kg", "min": 0},
            {"id": "treatment_body_weight_kg", "label": "Treatment BW", "default": 2.806, "unit": "kg", "min": 0},
            {"id": "control_mortality_pct", "label": "Control Mortality", "default": 4, "unit": "%", "min": 0, "max": 100},
            {"id": "treatment_mortality_pct", "label": "Treatment Mortality", "default": 1.67, "unit": "%", "min": 0, "max": 100},
        ],
        "output_metrics": ["investment_total", "benefit_total", "net_profit_total", "roi", "benefit_per_bird", "cost_per_bird"],
        "benefit_components": ["weight_gain_benefit", "mortality_benefit"],
    },
    "thermogard_prevention": {
        "product_name": "Thermogard Prevention",
        "category": "Water Medication",
        "application": "Prevention",
        "form": "Liquid",
        "calculation_engine": "thermogard",
        "inputs": [
            {"id": "flock_size", "label": "Flock Size", "default": 1000, "unit": "birds", "min": 1},
            {"id": "medication_start_day", "label": "Medication Start Day", "default": 15, "unit": "day", "min": 0},
            {"id": "medication_end_day", "label": "Medication End Day", "default": 25, "unit": "day", "min": 1},
            {"id": "morning_water_l", "label": "Morning Water", "default": 30, "unit": "L/day", "min": 0},
            {"id": "afternoon_water_l", "label": "Afternoon Water", "default": 30, "unit": "L/day", "min": 0},
            {"id": "product_price_per_liter", "label": "Product Price", "default": 1000, "unit": "₹/L", "min": 0},
            {"id": "preventive_dose_ml", "label": "Preventive Dose", "default": 30, "unit": "mL", "min": 0},
            {"id": "average_mortality_pct", "label": "Average Mortality", "default": 50, "unit": "%", "min": 0, "max": 100},
            {"id": "weight_gain_kg", "label": "Weight Gain", "default": 40, "unit": "kg", "min": 0},
            {"id": "mortality_saving_value", "label": "Mortality Saving", "default": 4400, "unit": "₹", "min": 0},
        ],
        "output_metrics": ["investment_total", "benefit_total", "net_profit_total", "roi", "cost_per_bird", "benefit_per_bird"],
        "benefit_components": ["weight_gain_benefit", "mortality_benefit"],
    },
    "thermogard_treatment": {
        "product_name": "Thermogard Treatment",
        "category": "Water Medication",
        "application": "Treatment",
        "form": "Liquid",
        "calculation_engine": "thermogard",
        "inputs": [
            {"id": "flock_size", "label": "Flock Size", "default": 1000, "unit": "birds", "min": 1},
            {"id": "medication_start_day", "label": "Medication Start Day", "default": 15, "unit": "day", "min": 0},
            {"id": "medication_end_day", "label": "Medication End Day", "default": 25, "unit": "day", "min": 1},
            {"id": "morning_water_l", "label": "Morning Water", "default": 30, "unit": "L/day", "min": 0},
            {"id": "afternoon_water_l", "label": "Afternoon Water", "default": 30, "unit": "L/day", "min": 0},
            {"id": "product_price_per_liter", "label": "Product Price", "default": 1000, "unit": "₹/L", "min": 0},
            {"id": "treatment_dose_ml", "label": "Treatment Dose", "default": 60, "unit": "mL", "min": 0},
            {"id": "average_mortality_pct", "label": "Average Mortality", "default": 50, "unit": "%", "min": 0, "max": 100},
            {"id": "weight_gain_kg", "label": "Weight Gain", "default": 30, "unit": "kg", "min": 0},
            {"id": "mortality_saving_value", "label": "Mortality Saving", "default": 7200, "unit": "₹", "min": 0},
        ],
        "output_metrics": ["investment_total", "benefit_total", "net_profit_total", "roi", "cost_per_bird", "benefit_per_bird"],
        "benefit_components": ["weight_gain_benefit", "mortality_benefit"],
    },
}


def get_product_config(product_id: str):
    return PRODUCT_DEFINITIONS[product_id]


def get_product_default_values(product_id: str):
    cfg = PRODUCT_DEFINITIONS[product_id]
    return {field["id"]: field["default"] for field in cfg["inputs"]}


def get_display_name(product_id: str):
    return PRODUCT_DEFINITIONS[product_id]["product_name"]
